# Generated by Django 5.2.7 on 2025-11-26 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='votereceipt',
            options={'ordering': ['-voted_at']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order on ballot'),
        ),
        migrations.AddField(
            model_name='election',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Leave empty for global elections', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='election',
            name='ended_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='ended_early_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='ended_early_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='ended_early_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='votereceipt',
            name='receipt_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election'),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Must be True for voting to be allowed'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election'),
        ),
        migrations.AlterField(
            model_name='votereceipt',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='elections.election'),
        ),
        migrations.AlterField(
            model_name='votereceipt',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
